version: '3.1'

services:

  app:
    depends_on:
      - db
      - redis
    image: booklibrary:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      REDIS_HOST: redis

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: booklibrary
      MYSQL_USER: booklibrary
      MYSQL_PASSWORD: booklibrary
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    command: redis-server --requirepass redispw
    ports:
      - "6379:6379"
